version: '3'
services:
  frontend:
    image: 634780534046.dkr.ecr.us-east-2.amazonaws.com/quizzing/q:latest
    container_name: q_stage_web
    restart: always
    networks:
      - q_stage
      - web
    working_dir: /app
    volumes:
      - ./application:/app
    stdin_open: true
    tty: true
    command: bash -l -c "mongrel_rails start -e staging"
  db:
    image: mysql:5.5
    container_name: q_stage_db
    restart: always
    ports:
      - 127.0.0.1:3309:3306
    networks:
      - q_stage
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=qs209242
      - MYSQL_DATABASE=q_stage
      - MYSQL_USER=qsite
      - MYSQL_PASSWORD=qs209242

networks:
  q_stage:
    external: false
  web:
    external: true