version: '3'
services:
  frontend:
    image: 634780534046.dkr.ecr.us-east-2.amazonaws.com/quizzing/q:latest
    container_name: q_web
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
    #command: tail -f /dev/null
    command: bash -l -c "mongrel_rails start"
  db:
    image: mysql:5.5
    container_name: q_db
    ports:
      - 3306:3306
    volumes:
      - ./sql/import.201901.sql:/docker-entrypoint-initdb.d/import.sql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=q_dev
      - MYSQL_USER=qsite
      - MYSQL_PASSWORD=qs209242