development:
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  host: q_db
  database: q_dev
  username: qsite
  password: qs209242
  pool: 5

test:
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  database: q_dev
  username: qsite
  password: qs209242
  pool: 5

staging:
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  database: q_dev
  username: qsite
  password: qs209242
  pool: 5

production:
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  database: q
  username: qsite
  password: qs209242
  pool: 5
