development:
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  database: q2016_dev
  username: qsite
  password: qs209242
  pool: 5

test:
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  database: q2016_test
  username: qsite
  password: qs209242
  pool: 5

staging:
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  database: q2016_staging
  username: qsite
  password: qs209242
  pool: 5

production:
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  database: q2016
  username: qsite
  password: qs209242
  pool: 5
