development:
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  host: q_dev_db
  database: q_dev
  username: username
  password: password
  pool: 5

test:
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  database: q_dev
  username: username
  password: password
  pool: 5

staging:
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  host: q_stage_db
  database: q_stage
  username: username
  password: password
  pool: 5

production:
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  host: q_db
  database: q
  username: username
  password: password
  pool: 5
