development: &non_production_settings
  site_url: http://localhost:3000
  site_name: Quizzing Events DEV
  admin_email: Quizzing Events <info@quizzingevents.com>
  test_mode: true
  regional_code: regionals2018
  convio_url: https://secure2.convio.net/cn/site/Donation2?df_id=19881&19881.donation=form1&set.DonationLevel=21862&df_preview=1
  
test:
  <<: *non_production_settings

staging:
  site_url: http://dev.quizzingevents.com
  site_name: Quizzing Events
  admin_email: Quizzing Events <info@quizzingevents.com>
  test_mode: true
  regional_code: regionals2018
  convio_url: https://secure2.convio.net/cn/site/Donation2?df_id=19881&19881.donation=form1&set.DonationLevel=21862&df_preview=1
  
production:
  site_url: http://www.quizzingevents.com
  site_name: Quizzing Events
  admin_email: Quizzing Events <info@quizzingevents.com>
  test_mode: false
  regional_code: regionals2018
  convio_url: https://secure2.convio.net/cn/site/Donation2?df_id=19861&19861.donation=form1&set.DonationLevel=21862
