development: &non_production_settings
  site_url: http://localhost:3000
  public_site_url: https://www.quizzingevents.com
  site_name: Quizzing Events DEV
  admin_email: Quizzing Events <info@quizzingevents.com>
  test_mode: true
  cvent_post_url: https://sandbox-www.cvent.com/Events/APIs/Reg.aspx
  ecode: 42425fbd-074c-4de9-8d65-09d7b4364396
  
test:
  <<: *non_production_settings

staging:
  site_url: https://qdev.nazquizzing.org
  public_site_url: https://qdev.nazquizzing.org
  site_name: Quizzing Events
  admin_email: Quizzing Events <info@quizzingevents.com>
  test_mode: true
  cvent_post_url: https://sandbox-www.cvent.com/Events/APIs/Reg.aspx
  ecode: 42425fbd-074c-4de9-8d65-09d7b4364396
  
production:
  site_url: https://www.quizzingevents.com
  public_site_url: https://www.quizzingevents.com
  site_name: Quizzing Events
  admin_email: Quizzing Events <info@quizzingevents.com>
  test_mode: false
  cvent_post_url: https://www.cvent.com/Events/APIs/Reg.aspx
  ecode: d5f126c9-a5af-40a4-86e0-40e90c968098
