development: &non_production_settings
  site_url: http://localhost:3000
  site_name: Quizzing Events DEV
  admin_email: Quizzing Events <info@quizzingevents.com>
  test_mode: true
  regional_code: regionals2018
  cvent_url: http://www.cvent.com/d/nrqtzj/4W
  
test:
  <<: *non_production_settings

staging:
  site_url: http://dev.quizzingevents.com
  site_name: Quizzing Events
  admin_email: Quizzing Events <info@quizzingevents.com>
  test_mode: true
  regional_code: regionals2018
  cvent_url: http://www.cvent.com/d/nrqtzj/4W
  
production:
  site_url: http://www.quizzingevents.com
  site_name: Quizzing Events
  admin_email: Quizzing Events <info@quizzingevents.com>
  test_mode: false
  regional_code: regionals2018
  cvent_url: http://www.cvent.com/d/nrqtzj/4W
