development: &non_production_settings
  site_url: http://localhost:3000
  site_name: Quizzing Events DEV
  admin_email: Quizzing Events <info@quizzingevents.com>
  test_mode: true
  ecode: 42425fbd-074c-4de9-8d65-09d7b4364396
  
test:
  <<: *non_production_settings

staging:
  site_url: http://dev.quizzingevents.com
  site_name: Quizzing Events
  admin_email: Quizzing Events <info@quizzingevents.com>
  test_mode: true
  ecode: 42425fbd-074c-4de9-8d65-09d7b4364396
  
production:
  site_url: http://www.quizzingevents.com
  site_name: Quizzing Events
  admin_email: Quizzing Events <info@quizzingevents.com>
  test_mode: false
  ecode: 61179253-75fc-4279-a70a-c6190fa6b171
